<a href="https://colab.research.google.com/github/hdat1509/ThToancaocap/blob/main/chuong5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

TH 1

In [15]:
from sympy import sqrt, simplify, count_ops, oo

In [ ]:
x=3

In [ ]:
print(x)

3


In [ ]:
import math
x = math.sqrt(1+x) 

In [ ]:
print(x)

2.0


TH 2

In [ ]:
import math
x=3
lap=1
while  (x != math.sqrt(x+1)):
  x = math.sqrt(1+x) 
  lap=lap+1
print(x)
print(lap)

1.618033988749895
32


TH 3

In [ ]:
import sympy as sp 
from sympy import Symbol 
x = Symbol('x') 
sp.solve(x-sp.sqrt(1+x),x) 

[1/2 + sqrt(5)/2]

Th 4

In [25]:
import numpy as np 
v1 = np.array([1., 2., 3.])  # tạo vector 3 chiều 
v2 = np.array([2., 1., 0.]) 
v3 = v1 + v2     # cộng vector 
v3 

array([3., 3., 3.])

In [ ]:
3*v1  + 2*v2 

array([7., 8., 9.])

In [12]:
[1., 2., 3.] + [2., 1., 0.] 

[1.0, 2.0, 3.0, 2.0, 1.0, 0.0]

In [ ]:
 3*[1, 2, 3] + 2*[2, 1, 0] 

[1, 2, 3, 1, 2, 3, 1, 2, 3, 2, 1, 0, 2, 1, 0]

In [26]:
v4 = np.hstack([v1, v2])
v4

array([1., 2., 3., 2., 1., 0.])

In [27]:
v5 = np.dot(v1, v2)
v5

4.0

In [29]:
angles = np.linspace(0, np.pi/2, 5)
angles

array([0.        , 0.39269908, 0.78539816, 1.17809725, 1.57079633])

In [30]:
np.sin(angles)

array([0.        , 0.38268343, 0.70710678, 0.92387953, 1.        ])

In [31]:
from sympy import sin as sysin 
angles = np.linspace(0, np.pi/2, 5) 
sinangle = np.zeros(5)     # tương đương 
sinangle = np.array([0.0, 0.0, 0.0, 0.0, 0.0]) 
len(angles)  # kiểm tra kích thước/số chiều của vector angles. 
for i in range(len(angles)): sinangle[i] = sysin(angles[i]) 
sinangle

array([0.        , 0.38268343, 0.70710678, 0.92387953, 1.        ])

In [32]:
import sympy as sy 
sy.sin(angles)

AttributeError: ignored

TH 5

In [33]:
import numpy as np 
goc = np.pi/3 
A = np.array([ [np.cos(goc), -np.sin(goc)], 
 [np.sin(goc), np.cos(goc)] ])

In [34]:
A

array([[ 0.5      , -0.8660254],
       [ 0.8660254,  0.5      ]])

In [35]:
V = np.array([1. , 0. ]) 
Y = np.dot(A, V) 
Y

array([0.5      , 0.8660254])

TH 6

In [38]:
from numpy import diff 
dx = 0.1 
y = [1, 2, 3, 4, 4, 6, 6]

In [39]:
diff(y)

array([1, 1, 1, 0, 2, 0])

In [40]:
dy = diff(y)/dx
dy

array([10., 10., 10.,  0., 20.,  0.])

TH 7

In [50]:
from sympy.geometry import*

In [51]:
P1 = Point(0, 0) 
P2 = Point(3, 4) 
P3 = Point(2, -1) 
P4 = Point(-1, 5) 

In [52]:
S1 = Segment(P1, P2) 
S2 = Segment(P3, P4)

In [53]:
Point.is_collinear(P1, P2, P3) 

False

In [54]:
S1.length

5

In [55]:
S2.midpoint

Point2D(1/2, 2)

In [56]:
S1.slope 

4/3

In [57]:
S1.intersection(S2) 

[Point2D(9/10, 6/5)]

In [58]:
Segment.angle_between(S1, S2) 

acos(sqrt(5)/5)

In [59]:
S1.contains(P3) 

False

In [60]:
L1 = Line(P1, P2) 
L1.equation() 

-4*x + 3*y

In [61]:
L1.is_parallel(S1) 

True

In [62]:
L1.is_parallel(S2)

False

TH 8

In [65]:
import sympy
x = Symbol('x') 
f = x * sin(1/x) 
c = Symbol('c') 
delta = Symbol('delta') 
c = 0 
delta = 1/4 
sympy.plot(f,(x, c - delta, c + delta))

NameError: ignored

TH 9

In [66]:
 from sympy import Symbol, solve, Derivative 
 x = Symbol('x') 
 f = -x**2+4*x-3 
 d1=Derivative(f, x).doit() 
 cuctri = solve(d1) 
 cuctri 
 [2] 
 A = cuctri[0] 
 d2 = Derivative(d1, x).doit() 
 d2.subs({x:A}).evalf() 


-2.00000000000000

In [68]:
x_min=0 
x_max=4 
f.subs({x:A}).evalf() 

1.00000000000000

In [69]:
 f.subs({x:x_min}).evalf() 

-3.00000000000000

In [70]:
f.subs({x:x_max}).evalf() 

-3.00000000000000

TH 10